import { Task } from '@/features/tasks/TaskTypes';

const now = new Date().toISOString();
const tomorrow = new Date();
tomorrow.setDate(tomorrow.getDate() + 1);
const nextWeek = new Date();
nextWeek.setDate(nextWeek.getDate() + 7);
const nextMonth = new Date();
nextMonth.setDate(nextMonth.getDate() + 30);

export const demoTasks: Task[] = [
  // UNASSIGNED tasks in Task Panel - Various scenarios
  {
    id: 'demo-1',
    title: 'Review quarterly budget report',
    description: 'Analyze Q4 expenses and prepare recommendations for next quarter. Include cost-benefit analysis and ROI calculations.',
    dueDate: tomorrow.toISOString().split('T')[0],
    urgent: false,
    important: true,
    quadrant: 'UNASSIGNED',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-2', 
    title: 'Fix critical login authentication bug',
    description: 'Users unable to login due to authentication service timeout. Affects 1000+ users daily.',
    dueDate: new Date().toISOString().split('T')[0],
    urgent: true,
    important: true,
    quadrant: 'UNASSIGNED',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-3',
    title: 'Plan annual team building retreat',
    description: 'Organize quarterly team outing and team building activities. Research venues and activities.',
    dueDate: nextMonth.toISOString().split('T')[0],
    urgent: false,
    important: false,
    quadrant: 'UNASSIGNED',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-15',
    title: 'Simple task without description',
    urgent: false,
    important: true,
    quadrant: 'UNASSIGNED',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-16',
    title: 'Overdue task example',
    description: 'This task demonstrates how overdue tasks appear with warning indicators.',
    dueDate: new Date(Date.now() - 86400000).toISOString().split('T')[0], // Yesterday
    urgent: true,
    important: true,
    quadrant: 'UNASSIGNED',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },

  // DO quadrant - Urgent + Important (Crisis Management)
  {
    id: 'demo-4',
    title: 'Handle client emergency - Server outage',
    description: 'Production server down for major client - needs immediate attention. Critical business impact.',
    dueDate: new Date().toISOString().split('T')[0],
    urgent: true,
    important: true,
    quadrant: 'DO',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-5',
    title: 'Submit quarterly tax documents',
    description: 'Corporate tax filing deadline is today - penalty fees apply after deadline',
    dueDate: new Date().toISOString().split('T')[0],
    urgent: true,
    important: true,
    quadrant: 'DO',
    completed: true,
    completedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-17',
    title: 'Resolve security vulnerability',
    description: 'Critical security patch required for user authentication system.',
    dueDate: new Date().toISOString().split('T')[0],
    urgent: true,
    important: true,
    quadrant: 'DO',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },

  // SCHEDULE quadrant - Not Urgent + Important (Strategic Planning)
  {
    id: 'demo-6',
    title: 'Complete Q1 project planning & roadmap',
    description: 'Define scope, timeline, resources, and milestones for next quarter project. Include risk assessment and stakeholder alignment.',
    dueDate: nextWeek.toISOString().split('T')[0],
    urgent: false,
    important: true,
    quadrant: 'SCHEDULE',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-7',
    title: 'Update team development documentation',
    description: 'Review and update development workflow documentation, coding standards, and onboarding guides',
    dueDate: nextWeek.toISOString().split('T')[0],
    urgent: false,
    important: true,
    quadrant: 'SCHEDULE',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-18',
    title: 'Plan professional development goals',
    description: 'Create learning objectives and skill development plan for team members.',
    dueDate: nextMonth.toISOString().split('T')[0],
    urgent: false,
    important: true,
    quadrant: 'SCHEDULE',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-19',
    title: 'Long-term strategic planning completed',
    description: 'Successfully completed the annual strategic planning session with all stakeholders.',
    urgent: false,
    important: true,
    quadrant: 'SCHEDULE',
    completed: true,
    completedAt: now,
    createdAt: now,
    updatedAt: now,
  },

  // DELEGATE quadrant - Urgent + Not Important (Admin Tasks)
  {
    id: 'demo-8',
    title: 'Schedule Q4 vendor contract meetings',
    description: 'Coordinate meetings with all software vendors for contract renewal. Delegate to procurement team.',
    dueDate: tomorrow.toISOString().split('T')[0],
    urgent: true,
    important: false,
    quadrant: 'DELEGATE',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-9',
    title: 'Order monthly office supplies',
    description: 'Printer paper, pens, coffee, and other office essentials are running low. Assign to office manager.',
    dueDate: new Date().toISOString().split('T')[0],
    urgent: true,
    important: false,
    quadrant: 'DELEGATE',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-20',
    title: 'Book travel for conference',
    description: 'Need flights and hotel for next week\'s industry conference. Delegate to travel coordinator.',
    dueDate: tomorrow.toISOString().split('T')[0],
    urgent: true,
    important: false,
    quadrant: 'DELEGATE',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-21',
    title: 'Process expense reports',
    description: 'Monthly expense report processing completed by accounting team.',
    urgent: true,
    important: false,
    quadrant: 'DELEGATE',
    completed: true,
    completedAt: now,
    createdAt: now,
    updatedAt: now,
  },

  // DELETE quadrant - Not Urgent + Not Important (Low Priority)
  {
    id: 'demo-10',
    title: 'Watch optional industry webinar series',
    description: 'Optional webinar series about emerging technology trends. Nice to have but not essential.',
    dueDate: nextMonth.toISOString().split('T')[0],
    urgent: false,
    important: false,
    quadrant: 'DELETE',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-11',
    title: 'Organize personal desk workspace',
    description: 'Clean and organize personal workspace drawer and desk area for better productivity',
    urgent: false,
    important: false,
    quadrant: 'DELETE',
    completed: true,
    completedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-22',
    title: 'Browse new productivity apps',
    description: 'Research new productivity and time management applications. Low priority exploration.',
    urgent: false,
    important: false,
    quadrant: 'DELETE',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'demo-23',
    title: 'Read industry magazine backlog',
    description: 'Catch up on accumulated industry magazines and publications.',
    urgent: false,
    important: false,
    quadrant: 'DELETE',
    completed: false,
    createdAt: now,
    updatedAt: now,
  },
];